app01/urls.py
from django.conf.urls import url,include
from app01 import views
urlpatterns = [
    url(r'^$', views.dashboard),
    url(r'^customers/$', views.customers,name='customer_list'),
    url(r'^customers/(\d+)/$', views.customer_detail,name='customer_detail'),#取别名
    url(r'^customers/add/$', views.customer_add,name='customer_add'),

    url(r'^courses/$', views.courses,name='course_list'),
    url(r'^courses/(\d+)/$', views.course_detail,name='course_detail'),
    url(r'^courses/add/$', views.course_add,name='course_add'),

    url(r'^schools/$', views.schools,name='school_list'),
    url(r'^schools/(\d+)/$', views.school_detail,name='school_detail'),
    url(r'^schools/add/$', views.school_add,name='school_add'),

    url(r'^userprofiles/$', views.userprofiles,name='userprofile_list'),
    url(r'^userprofiles/(\d+)/$', views.userprofile_detail,name='userprofile_detail'),
    url(r'^userprofiles/add/$', views.userprofile_add,name='userprofile_add'),

    url(r'^courserecords/$', views.courserecords,name='courserecord_list'),
    url(r'^courserecords/(\d+)/$', views.courserecord_detail,name='courserecord_detail'),
    url(r'^courserecords/add/$', views.courserecord_add,name='courserecord_add'),

    url(r'^studyrecords/$', views.studyrecords,name='studyrecord_list'),
    url(r'^studyrecords/(\d+)/$', views.studyrecord_detail,name='studyrecord_detail'),
    url(r'^studyrecords/add/$', views.studyrecord_add,name='studyrecord_add'),

    url(r'^consultrecords/$', views.consultrecords,name='consultrecord_list'),
    url(r'^consultrecords/(\d+)/$', views.consultrecord_detail,name='consultrecord_detail'),
    url(r'^consultrecords/add/$', views.consultrecord_add,name='consultrecord_add'),

    url(r'^classlists/$', views.classlists,name='classlist_list'),
    url(r'^classlists/(\d+)/$', views.classlist_detail,name='classlist_detail'),
    url(r'^classlists/add/$', views.classlist_add,name='classlist_add'),



]

stu_man/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^accounts/login/$', views.acc_login),
    url(r'^accounts/logout/$', views.acc_logout),
    url(r'^crm/', include('app01.urls'))
]

app01/models.py
from django.db import models

# Create your models here.
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


#定义在外面就不能通过各模型类取到这个变量了
class_type_choices = (
    ('online',u'网络班'),
    ('offline_weekend',u'周末面授班'),
    ('offline_fulltime',u'脱产面授班'),
)

class UserProfile(models.Model):
    #继承内置的用户认证机制，可以实现继承并扩展自己的字段
    #在数据库中实现就是foreignkey，所以这种onetoone只能在django层面限制，不能在数据库里限制
    #
    user = models.OneToOneField(User)
    name = models.CharField(u'姓名',max_length=32)
    school = models.ForeignKey('School',verbose_name='校区',default=1)
    def __str__(self):
        return self.name

    #权限定义，与表结构本身没关系，可以写到任意表结构定义下面
    class Meta:
        permissions = (
            #讲师只能看，销售有全部权限
            ('view_customer_list',u'可以查看客户列表'),
            ('view_customer_info',u'可以查看客户详细信息'),
            ('edit_own_customer_info',u'可以修改自己的客户信息'),
            ('add_customer_get',u'可以进入新增客户界面'),
            ('add_customer_post', u'可以提交新增客户信息'),
            ('batch_own_customer_info', u'可以批量操作自己的客户信息'),

            #讲师有全部权限，销售、学员只能看
            ('view_courserecord_list', u'可以查看开课记录列表'),
            ('batch_own_courserecord_info',u'可以批量操作自己的开课记录'),
            ('add_courserecord_info',u'可以新增开课记录'),

            #讲师有全部权限，销售、学员只能看
            ('view_classlist_list', u'可以查看班级列表'),
            ('edit_classlist_info', u'可以修改班级'),
            ('batch_own_classlist_info', u'可以批量操作班级'),
            ('add_classlist_info', u'可以新增班级'),

            #讲师有全部权限，销售、学员只能看
            ('view_studyrecord_list', u'可以查看学习记录列表'),
            ('edit_studyrecord_info', u'可以修改学习记录'),
            ('batch_studyrecord_info', u'可以批量操作学习记录'),
            ('add_studyrecord_info', u'可以新增学习记录'),

            #校长有权限
            ('view_userprofile_list', u'可以查看用户列表'),
            ('view_school_list', u'可以查看校区列表'),

        )


class School(models.Model):
    name = models.CharField(u'校区名称',max_length=64,unique=True)
    addr = models.CharField(u'地址',max_length=128)
    #staffs = models.ManyToManyField('UserProfile',blank=True,verbose_name='成员')
    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(u'课程名称',max_length=128,unique=True)
    price = models.IntegerField(u'面授价格')
    online_price = models.IntegerField(u'网络班价格')
    brief = models.TextField(u'课程简介')
    def __str__(self):
        return self.name

class ClassList(models.Model):
    course = models.ForeignKey(Course)
    course_type = models.CharField(u'课程类型',choices=class_type_choices,max_length=32)
    semester = models.IntegerField(u'学期')
    start_date = models.DateField(u'开班日期')
    graduate_date = models.DateField(u'毕业日期',blank=True,null=True)
    teachers = models.ManyToManyField(UserProfile,verbose_name=u'讲师')
    def __str__(self):
        #显示选项中的中文
        return u'%s(%s)[%s期]' % (self.course.name,self.get_course_type_display(),self.semester)
    class Meta:
        verbose_name = u'班级列表'
        verbose_name_plural = u'班级列表'
        #联合唯一
        unique_together = ('course','course_type','semester')

class Customer(models.Model):
    qq = models.CharField(u'QQ号',max_length=64,unique=True)
    name = models.CharField(u'姓名',max_length=32,blank=True,null=True)
    phone = models.BigIntegerField(u'手机',blank=True,null=True)
    stu_id = models.CharField(u'学号',blank=True,null=True,max_length=64)
    source_choices = (
        ('qq',u'qq群'),
        ('referral',u'内部转介绍'),
        ('51cto',u'51cto'),
        ('agent',u'招生代理'),
        ('others',u'其它'),
    )
    source = models.CharField(u'客户来源',max_length=64,choices=source_choices,default='qq')
    #加一个推荐人字段，关联到这个表的其它记录,self要加引号
    referral_from = models.ForeignKey('self',
                                      verbose_name=u'转介绍自学员',
                                      help_text='若客户是转介绍自学员，填写学员姓名',
                                      blank=True,
                                      null=True,
                                      # 这个一定要有，反查时用这个名
                                      related_name='internal_referral')

    course = models.ForeignKey(Course,verbose_name=u'咨询课程')
    class_type_choices = (
        ('online', u'网络班'),
        ('offline_weekend', u'周末面授班'),
        ('offline_fulltime', u'脱产面授班'),
    )
    class_type = models.CharField(u'班级类型',max_length=64,choices=class_type_choices)
    customer_note = models.TextField(u'客户咨询详情',help_text=u'客户咨询的对话记录')
    status_choices = (
        ('signed',u'已报名'),
        ('unregistered',u'未报名'),
        ('graduated',u'已毕业'),
        ('dropoff',u'已退学'),
    )
    status = models.CharField(u'客户状态',choices=status_choices,max_length=64,default='unregistered')
    consultant = models.ForeignKey(UserProfile,verbose_name=u'课程顾问')
    date = models.DateField(u'咨询日期',auto_now_add=True)
    #多对多或外键字段可以不填的情况，只要加上blank=True
    class_list = models.ManyToManyField(ClassList,verbose_name=u'已报名班级',blank=True)
    def __str__(self):
        return u'%s, %s' % (self.qq,self.name)

class ConsultRecord(models.Model):
    customer = models.ForeignKey(Customer,verbose_name=u'咨询客户')
    note = models.TextField(u'跟进内容')
    status_choices = (
        (1,u'近期无报名计划'),
        (2,u'2个月内报名'),
        (3,u'1个月内报名'),
        (4,u'2周内报名'),
        (5,u'1周内报名'),
        (6,u'2天内报名'),
        (7,u'已报名'),
    )
    status = models.IntegerField(u'状态',choices=status_choices,help_text=u'选择此客户的状态')
    consultant = models.ForeignKey(UserProfile,verbose_name=u'跟进人')
    date = models.DateField(u'跟进日期',auto_now_add=True)
    def __str__(self):
        return u'%s, %s' % (self.customer,self.status)
    class Meta:
        verbose_name = u'客户咨询跟进记录'
        verbose_name_plural = u'客户咨询跟进记录'

class CourseRecord(models.Model):
    course = models.ForeignKey(ClassList,verbose_name=u'班级（课程）')
    day_num = models.IntegerField(u'节次',help_text=u'填写第几节课')
    date = models.DateField(auto_now_add=True,verbose_name=u'上课日期')
    teacher = models.ForeignKey(UserProfile,verbose_name=u'讲师')
    def __str__(self):
        return u'%s 第%s天' % (self.course,self.day_num)
    class Meta:
        verbose_name = u'上课记录'
        verbose_name_plural = u'上课记录'
        unique_together = ('course','day_num')

class StudyRecord(models.Model):
    course_record = models.ForeignKey(CourseRecord,verbose_name=u'第几天课程')
    student = models.ForeignKey(Customer,verbose_name=u'学员')
    record_choices = (
        ('checked',u'已签到'),
        ('late',u'迟到'),
        ('absence',u'缺课'),
        ('leave_early',u'早退'),
    )
    record = models.CharField(u'上课记录',choices=record_choices,default='checked',max_length=32)
    score_choices = (
        (100,'A+'),
        (90,'A'),
        (85,'B+'),
        (80,'B'),
        (70,'B-'),
        (60,'C+'),
        (50,'C'),
        (0,'D'),
        (-1,'N/A'),
        (-100,'COPY'),
    )
    score = models.IntegerField(u'本节成绩',choices=score_choices,default=-1)
    date = models.DateField(auto_now_add=True)
    note = models.CharField(u'备注',max_length=255,blank=True,null=True)
    def __str__(self):
        return u'%s，学员：%s，记录：%s，成绩：%s' % (self.course_record,self.student.name,self.record,self.score)
    class Meta:
        verbose_name = u'学员学习记录'
        verbose_name_plural = u'学员学习记录'
        unique_together = ('course_record','student')

app01/forms.py
from django.forms import Form,ModelForm
from app01 import models
from django.db.models import Count
from stu_man import settings

def get_filter_fields(cls):
    filter_fields = settings.FILTER_FIELDS.get(cls.__name__.lower())
    if filter_fields is None:
        return None
    #print('***filter fields:', filter_fields)
    field_list = cls._meta.local_fields#取出模型对应表的字段列表

    filter_dic = []
    for field in field_list:
        #print('***field_name:', field.attname)
        if field.attname in filter_fields:#只处理配置中存在的字段
            name = field.verbose_name#模型中定义的字段别名
            # print('***is relation:', bool(field.is_relation))
            if bool(field.is_relation):  # 如果是关联字段
                is_relation = True
                group_id = field.attname
                group_name = '%s__name' % field.attname[:-3]
                #print('***group_name:', group_name)
                #得到的是group by group_name后，取(group_id,count(group_name))两个字段组成的二元组列表
                val_list = cls.objects.all().values_list(group_id, group_name).annotate(Count(group_name))
                #print('***relation val_dic:', val_list)
            else:
                is_relation = False
                group_name = field.attname
                val_dic = cls.objects.all().values_list(group_name).annotate(Count(group_name))
                #加上选项对应的别名
                alias_list = dict(getattr(cls,'%s_choices' % group_name))
                val_list = []
                for i in val_dic:
                    tmp_list = list(i)
                    tmp_list.append(alias_list[i[0]])
                    val_list.append(tmp_list)

            filter_dic.append({'name': name, 'tags': list(val_list),'is_relation':is_relation,'field_name':field.attname})
    #print('***filter_dic:', filter_dic)
    return filter_dic

class CustomerModelForm(ModelForm):
    class Meta:
        #指定模式表单对应的模型
        model = models.Customer
        #模型中以下指定的字段不显示在表单中
        exclude = ()

    #给模式表单中的字段加自定义样式
    def __init__(self,*args,**kwargs):
        super(CustomerModelForm,self).__init__(*args,**kwargs)
        #self.fields['qq'].widget.attrs['class'] = 'form-control'

        #遍历模型里的所有字段，加上一些表单属性
        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({'class':'form-control'})

class CourseModelForm(ModelForm):
    class Meta:
        model = models.Course
        exclude = ()
    # 给模式表单中的字段加自定义样式
    def __init__(self, *args, **kwargs):
        super(CourseModelForm, self).__init__(*args, **kwargs)

        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({'class': 'form-control'})

class SchoolModelForm(ModelForm):
    class Meta:
        model = models.School
        exclude = ()
    # 给模式表单中的字段加自定义样式
    def __init__(self, *args, **kwargs):
        super(SchoolModelForm, self).__init__(*args, **kwargs)

        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({'class': 'form-control'})

class UserProfileModelForm(ModelForm):
    class Meta:
        model = models.UserProfile
        exclude = ()
    # 给模式表单中的字段加自定义样式
    def __init__(self, *args, **kwargs):
        super(UserProfileModelForm, self).__init__(*args, **kwargs)

        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({'class': 'form-control'})

class CourseRecordModelForm(ModelForm):
    class Meta:
        model = models.CourseRecord
        exclude = ()
    # 给模式表单中的字段加自定义样式
    def __init__(self, *args, **kwargs):
        super(CourseRecordModelForm, self).__init__(*args, **kwargs)

        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({'class': 'form-control'})

class StudyRecordModelForm(ModelForm):
    class Meta:
        model = models.StudyRecord
        exclude = ()
    # 给模式表单中的字段加自定义样式
    def __init__(self, *args, **kwargs):
        super(StudyRecordModelForm, self).__init__(*args, **kwargs)

        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({'class': 'form-control'})

class ConsultRecordModelForm(ModelForm):
    class Meta:
        model = models.ConsultRecord
        exclude = ()
    # 给模式表单中的字段加自定义样式
    def __init__(self, *args, **kwargs):
        super(ConsultRecordModelForm, self).__init__(*args, **kwargs)

        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({'class': 'form-control'})

class ClassListModelForm(ModelForm):
    class Meta:
        model = models.ClassList
        exclude = ()
    # 给模式表单中的字段加自定义样式
    def __init__(self, *args, **kwargs):
        super(ClassListModelForm, self).__init__(*args, **kwargs)

        for field_name in self.base_fields:
            field = self.base_fields[field_name]
            field.widget.attrs.update({'class': 'form-control'})

templates/app01/classlist_add.html
{% extends 'base.html' %}

{% block page-header %}
新增课程信息
{% endblock %}

{% block page-content %}
    <form action="{% url 'course_add' %}" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/classlist_detail.html
{% extends 'base.html' %}

{% block page-header %}
课程详细信息
{% endblock %}

{% block page-content %}
    <form action="" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/course_detail.html
{% extends 'base.html' %}

{% block page-header %}
课程详细信息
{% endblock %}

{% block page-content %}
    <form action="" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/courserecord_detail.html
{% extends 'base.html' %}

{% block page-header %}
开课记录详细信息
{% endblock %}

{% block page-content %}
    <form action="" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/customer_add.html
{% extends 'base.html' %}

{% block page-header %}
新增客户信息
{% endblock %}

{% block page-content %}
    <form action="{% url 'customer_add' %}" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/customer_detail.html
{% extends 'base.html' %}

{% block page-header %}
客户详细信息
{% endblock %}

{% block page-content %}
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        {% for field in customer_form %}
            <div class="form-group">
                {% if field.field.required %}
                <label class="col-sm-2 control-label">*{{ field.label }}</label>
                {% else %}
                <label style="font-weight: normal" class="col-sm-2 control-label">{{ field.label }}</label>
                {% endif %}
                <div class="col-sm-8">

                    {{ field }}
                    {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                        <li style="color:red;">{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="col-sm-10"><input class="btn btn-success pull-right" type="submit" value="提交"/></div>

    </form>

{% endblock %}

templates/app01/customers.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block page-header %}
客户信息列表
<a href="{% url 'customer_add' %}">
    <button type="button" class="btn btn-default pull-right">
      <span class="glyphicon glyphicon-plus"></span> ADD客户
    </button>
</a>
{% endblock %}

{% block page-content %}
<div class="panel panel-default">

    <div class="panel-heading" id="panel-heading">
        <div class="col-md-9 " >
            <form action="{% url url_alias %}?page=1{{ search_str }}" method="GET">
                {% for input in search_val_dic.items %}
                    <input type="hidden" name="{{ input.0 }}" value="{{ input.1 }}"/>
                {% endfor %}
                <div class="col-md-5">
                    <input name="find__qq" class="form-control" type="text" value="{{ find_list.1 }}" placeholder="输入QQ号" minlength="1" maxlength="20" required>
                </div>
                <div class="col-md-3 search-button">
                    <button type="submit" id="btn-submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span> 搜索
                    </button>
                    {% if filter_dic %}
                    <button type="button" id='btn-filter' class="btn btn-default">
                        <span class="glyphicon glyphicon-cog"></span>
                    </button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>

    {% include 'app01/filter_component.html' %}

    <table class="table table-hover">
    <thead>
    <tr>
        <th><input type="checkbox" name="all_ids" value=""/></th>
        <th>ID</th>
        <th>QQ</th>
        <th>姓名</th>
        <th>客户来源</th>
        <th>咨询课程</th>
        <th>班级类型</th>
        <th>客户状态</th>
        <th>课程顾问</th>
        <th>日期</th>
        <th>客户备注</th>
    </tr>
    </thead>
    <tbody>
    {% for customer in data_list %}
        <tr>
            <td><input type="checkbox" name="id" value="{{ customer.id }}"/> </td>
            <td><a href="{% url 'customer_detail' customer.id %}">{{ forloop.counter }}</a></td>
            <td>{{ customer.qq }}</td>
            <td>{{ customer.name }}</td>
            <td>{{ customer.source }}</td>
            <td>{{ customer.course }}</td>
            <td>{{ customer.get_class_type_display }}</td>
            <td class="{{ customer.status }}">{{ customer.get_status_display }}</td>
            <td>{{ customer.consultant }}</td>
            <td>{{ customer.date }}</td>
            <td>{{ customer.customer_note|truncatechars:30 }}</td>
            </tr>
    {% endfor %}
    </tbody>
</table>
    <div class="panel-footer">
        {% if actions %}
        <div class="row">
            <select name="data-action" class="form-control data-action action-select">
            {% for action in actions %}
                <option value="{{ action.0 }}">{{ action.1 }}</option>
            {% endfor %}
            </select>
            <button class="form-control data-action action-ok">GO</button>{% csrf_token %}
        </div>
        {% endif %}
        <!--整个分页功能都做成标签-->
        <nav>{% pagination_bar data_list search_str find_list %}</nav>
    </div>
</div>

{% endblock %}

templates/app01/form_content.html
{% csrf_token %}
{% for field in data_form %}
    <div class="form-group">
        {% if field.field.required %}
        <label class="col-sm-2 control-label">*{{ field.label }}</label>
        {% else %}
        <label style="font-weight: normal" class="col-sm-2 control-label">{{ field.label }}</label>
        {% endif %}
        <div class="col-sm-8">
            {{ field }}
            {% if field.errors %}
            <ul>
                {% for error in field.errors %}
                <li style="color:red;">{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
{% endfor %}
<div class="col-sm-10"><input class="btn btn-success pull-right" type="submit" value="提交"/></div>

templates/app01/school_add.html
{% extends 'base.html' %}

{% block page-header %}
新增校区信息
{% endblock %}

{% block page-content %}
    <form action="{% url 'school_add' %}" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/studyrecord_add.html
{% extends 'base.html' %}

{% block page-header %}
新增学员上课记录信息
{% endblock %}

{% block page-content %}
    <form action="{% url 'studyrecord_add' %}" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/studyrecord_detail.html
{% extends 'base.html' %}

{% block page-header %}
学员上课记录详细信息
{% endblock %}

{% block page-content %}
    <form action="" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/studyrecords.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block page-header %}
学员上课记录列表
<a href="{% url 'studyrecord_add' %}">
    <button type="button" class="btn btn-default pull-right">
      <span class="glyphicon glyphicon-plus"></span> ADD学员上课记录
    </button>
</a>
{% endblock %}

{% block page-content %}
<div class="panel panel-default">

    <div class="panel-heading" id="panel-heading">
        <div class="col-md-9 " >
            <form action="{% url url_alias %}?page=1{{ search_str }}" method="GET">
                {% for input in search_val_dic.items %}
                    <input type="hidden" name="{{ input.0 }}" value="{{ input.1 }}"/>
                {% endfor %}
                <div class="col-md-5">
                    <input name="find__student__name" class="form-control" type="text" value="{{ find_list.1 }}" placeholder="输入学员姓名" minlength="1" maxlength="20" required>
                </div>
                <div class="col-md-3 search-button">
                    <button type="submit" id="btn-submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span> 搜索
                    </button>
                    {% if filter_dic %}
                    <button type="button" id='btn-filter' class="btn btn-default">
                        <span class="glyphicon glyphicon-cog"></span>
                    </button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>

    {% include 'app01/filter_component.html' %}

    <table class="table table-hover">
    <thead>
    <tr>
        <th><input type="checkbox" name="all_ids" value=""/></th>
        <th>ID</th>
        <th>学员</th>
        <th>第几天课程</th>
        <th>上课记录</th>
        <th>本节成绩</th>
        <th>上课日期</th>
        <th>备注</th>
    </tr>
    </thead>
    <tbody>
    {% for data in data_list %}
        <tr>
            <td><input type="checkbox" name="id" value="{{ data.id }}"/> </td>
            <td><a href="{% url 'studyrecord_detail' data.id %}">{{ forloop.counter }}</a></td>
            <td>{{ data.student }}</td>
            <td>{{ data.course_record }}</td>
            <td>{{ data.get_record_display }}</td>
            <td>{{ data.get_score_display }}</td>
            <td>{{ data.date }}</td>
            <td>{{ data.note }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

    <div class="panel-footer">
        {% if actions %}
        <div class="row">
            <select name="data-action" class="form-control data-action action-select">
            {% for action in actions %}
                <option value="{{ action.0 }}">{{ action.1 }}</option>
            {% endfor %}
            </select>
            <button class="form-control data-action action-ok">GO</button>{% csrf_token %}
        </div>
        {% endif %}
        <!--整个分页功能都做成标签-->
        <nav>{% pagination_bar data_list search_str find_list %}</nav>
    </div>
</div>

{% endblock %}

templates/app01/userprofile_add.html
{% extends 'base.html' %}

{% block page-header %}
新增用户信息
{% endblock %}

{% block page-content %}
    <form action="{% url 'userprofile_add' %}" method="post" class="form-horizontal">
        {% include 'app01/form_content.html' %}
    </form>

{% endblock %}

templates/app01/userprofiles.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block page-header %}
用户信息列表
<a href="{% url 'userprofile_add' %}">
    <button type="button" class="btn btn-default pull-right">
      <span class="glyphicon glyphicon-plus"></span> ADD用户
    </button>
</a>
{% endblock %}

{% block page-content %}
<div class="panel panel-default">

    <div class="panel-heading" id="panel-heading">
        <div class="col-md-9 " >
            <form action="{% url url_alias %}?page=1{{ search_str }}" method="GET">
                {% for input in search_val_dic.items %}
                    <input type="hidden" name="{{ input.0 }}" value="{{ input.1 }}"/>
                {% endfor %}
                <div class="col-md-5">
                    <input name="find__name" class="form-control" type="text" value="{{ find_list.1 }}" placeholder="输入用户姓名" minlength="1" maxlength="20" required>
                </div>
                <div class="col-md-3 search-button">
                    <button type="submit" id="btn-submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span> 搜索
                    </button>
                    {% if filter_dic %}
                    <button type="button" id='btn-filter' class="btn btn-default">
                        <span class="glyphicon glyphicon-cog"></span>
                    </button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>

    {% include 'app01/filter_component.html' %}

    <table class="table table-hover">
    <thead>
    <tr>
        <th>ID</th>
        <th>姓名</th>
        <th>所在校区</th>
        <th>关联账号</th>
    </tr>
    </thead>
    <tbody>
    {% for data in data_list %}
        <tr>
            <td><a href="{% url 'userprofile_detail' data.id %}">{{ data.id }}</a></td>
            <td>{{ data.name }}</td>
            <td>{{ data.school.name }}</td>
            <td>{{ data.user}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    <div class="panel-footer">
        <!--整个分页功能都做成标签-->
        <nav>{% pagination_bar data_list search_str find_list %}</nav>
    </div>
</div>

{% endblock %}